### ISSUE TITLE
GroupSids versus named AD groups

### ISSUE THREAD

**Issue by dodegaard** [artisticcheese/artisticcheesecontainer#2]
Thanks in advance for your help.  My challenge is that I am only seeing GroupSids from our AD instance coming into the integration and not something like "Domain Admin". I wondered if you ever saw this in your work with AD integration and ASP.NET Core.  Looking for a solution to this simple thing to allow the named attributes to be truly usable for group/role permissions.

**Comment by artisticcheese** [comment]
This instructions did not work for you? https://artisticcheese.wordpress.com/2017/09/10/asp-net-core-and-integrated-windows-authentication-in-nanoserver-container/

**Comment by dodegaard** [comment]
They seem to but instead of authenticating against a local SAM I am hitting the client's true AD during development and getting only GroupSids. It is showing Kerberos as a type but for some reason the names don't show which may be a limitation on permissions from their internal AD instance. Thanks.
