### ISSUE TITLE
Setup not compatibile with 1709 and Powershell-core 6.0.1

### ISSUE THREAD

**Issue by thehetz** [artisticcheese/artisticcheesecontainer#3]
Hi, these are great steps and work fine when working with versions of nanoserver prior to 1709.  However, since only Powershell core is available for version 1709 of nanoserver, what can we do?  I know that the WindowsPowershell modules can be installed, however that requires elevated privileges and there appears to be no way to get an elevated prompt in this hew version, is there?

Thanks!

**Comment by artisticcheese** [comment]
You mean `Enter-PSession` is not working or `docker exec`?

**Comment by thehetz** [comment]
Enter PSSession does not work because the required modules are not present in Powershell-core yet to my knowledge. They can be installed, however that requires elevated privileges. Docker exec works, but only for user sessions.  Passing in -u 0 returns an access denied message.  Bottom line is, I need to get an admin prompt in the new container but cannot figure out anyway to. Also, the command to start powershell has changed to pwsh.exe.  Image is located here: Microsoft/powershell:nanoserver

**Comment by artisticcheese** [comment]
You probably need to create github ticket in moby/mody for further guidance. I can see the same issue as you are.

**Comment by artisticcheese** [comment]
Here is what works
`docker exec -it -u Administrator --privileged <containerID> cmd.exe`
