### ISSUE TITLE
minor update -UseBasicParsing

### ISSUE THREAD

**Issue by dazinator** [artisticcheese/artisticcheesecontainer#4]
Excellent wiki so far, I have just started to go through it, thanks.

On this page: https://github.com/artisticcheese/artisticcheesecontainer/wiki/launching%20first%20container

I found that when doing Invoke-WebRequest I got this:

```
 > Invoke-WebRequest 172.22.224.108 | select -ExpandProperty headers
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or
Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:1
+ Invoke-WebRequest 172.22.224.108 | select -ExpandProperty headers
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
   d

```

I had to add a `-UseBasicParsing` flag to get this to work:

>  Invoke-WebRequest 172.22.224.108 -UseBasicParsing | select -ExpandProperty headers

> Key            Value
---            -----
Accept-Ranges  bytes
Content-Length 703
Content-Type   text/html
Date           Wed, 04 Apr 2018 20:27:13 GMT
ETag           "ad5ff35cbbd31:0"
Last-Modified  Tue, 13 Mar 2018 20:45:22 GMT
Server         Microsoft-IIS/10.0

Just a minor thing!

**Comment by artisticcheese** [comment]
Thanks, fixed.
